
services:
  caddy:
    build: .
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./conf.d:/etc/caddy/conf.d
      - ../caddy/apps:/etc/caddy/apps
      - ../caddy/imports:/etc/caddy/imports
      - ../caddy/sites-available:/etc/caddy/sites-available
      - ../caddy/sites-enabled:/etc/caddy/sites-enabled
      - data:/data
      - config:/config
    env_file:
      - ./local-config/secrets/caddy.env
      - ./network.env
    labels:
      at.grub1.auto-update: build
    networks:
      caddy:
        ipv4_address: 10.17.255.250

volumes:
  data:
  config:

networks:
  caddy:
    external: true
    name: caddy

